spring:

  datasource:
    url: jdbc:mysql://localhost:3306/case_study_3_1
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
      # table-name: SPRING_SESSION # Nếu cần cấu hình tên bảng
  logging:
    level:
      org.springframework.security: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: quangthai170402@gmail.com
    password: fdba bowh abym pwda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
